/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Saúde da aplicação (db e redis)
         * @description Público e fora do rate limit. 503 se db ou redis estiverem fora (o corpo traz o estado de cada componente em `data`).
         */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/meta/enums": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Enums e metadados para selects (esqueleto)
         * @description Esqueleto vazio na F1-06. Será protegido por bearerAuth na F1-10 (perfil: qualquer autenticado).
         */
        get: operations["metaEnums"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthData: {
            /** @enum {string} */
            app: "up";
            /** @enum {string} */
            db: "up" | "down";
            /** @enum {string} */
            redis: "up" | "down";
            /** @example 0.1.0 */
            version: string;
        };
        /** @description Envelope padrão de toda resposta. */
        Envelope: {
            /**
             * @description Definições globais da OpenAPI (info, servidor, segurança, schemas e respostas reutilizáveis).
             *     Os endpoints são anotados nos próprios controllers.
             * @enum {string}
             */
            status: "success" | "error";
            /** @example Operação realizada com sucesso. */
            message: string;
            errors: {
                [key: string]: string[];
            } | null;
            /** @description Objeto, lista ou null conforme o endpoint (qualquer tipo). */
            data: unknown;
            meta?: components["schemas"]["Pagination"];
        };
        /** @description Presente (`meta`) apenas em listas paginadas. */
        Pagination: {
            /** @example 1 */
            current_page: number;
            /** @example 15 */
            per_page: number;
            /** @example 0 */
            total: number;
            /** @example 1 */
            last_page: number;
        };
        /** @description Resposta de erro (401, 403, 404, 405, 409, 429, 500, 503). */
        ErrorEnvelope: {
            /** @enum {string} */
            status: "error";
            /** @example Recurso não encontrado. */
            message: string;
            /** @example null */
            errors: Record<string, never> | null;
            /**
             * @description Sempre null em erros.
             * @example null
             */
            data: unknown;
        };
        /** @description Erro de validação (422): `errors` mapeia campo → mensagens. */
        ValidationErrorEnvelope: {
            /** @enum {string} */
            status: "error";
            /** @example Os dados informados são inválidos. */
            message: string;
            /**
             * @example {
             *       "email": [
             *         "O campo email é obrigatório."
             *       ]
             *     }
             */
            errors: {
                [key: string]: string[];
            };
            /**
             * @description Sempre null em erros.
             * @example null
             */
            data: unknown;
        };
    };
    responses: {
        /** @description Não autenticado (401). */
        Unauthenticated: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Acesso negado (403). */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Recurso não encontrado (404). */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Conflito de regra de negócio (409). */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Dados inválidos (422). */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ValidationErrorEnvelope"];
            };
        };
        /** @description Limite de requisições excedido (429). */
        TooManyRequests: {
            headers: {
                /** @description Segundos até poder tentar novamente. */
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Erro interno (500), sem detalhes técnicos com APP_DEBUG=false. */
        ServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Todos os componentes ativos. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["HealthData"];
                    };
                };
            };
            /** @description Algum componente indisponível. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"] & {
                        data?: components["schemas"]["HealthData"];
                    };
                };
            };
        };
    };
    metaEnums: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Enums disponíveis (vazio por enquanto). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: {
                            enums?: Record<string, never>;
                        };
                    };
                };
            };
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["ServerError"];
        };
    };
}
