/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/audit-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lista o audit trail (somente leitura)
         * @description Permissão: audit.view (A). Ordenação fixa: event_at desc, id desc (`sort` é ignorado). `from`/`to` em ISO 8601 sobre event_at, inclusivos; data sem hora = dia inteiro em UTC (`from` às 00:00, `to` até 23:59:59.999999); `from` > `to` → 422. Não há escrita: POST/PUT/PATCH/DELETE → 405.
         */
        get: operations["auditLogsIndex"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit-logs/{audit_log}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Detalha um evento do audit trail
         * @description Permissão: audit.view (A). Inexistente → 404.
         */
        get: operations["auditLogsShow"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login (emite token Bearer)
         * @description Público. Só username + senha (v1.8); o e-mail serve apenas para a recuperação de senha. `username` passa por trim + minúsculas, sem validação de formato. Username inexistente (inclusive um e-mail digitado), usuário excluído ou senha errada → 422 em `errors.username` com a mesma mensagem genérica. Campo vazio → 422 por campo. Usuário inativo → 403 (somente com a senha correta). Rate limit: 5/min por username normalizado + IP e 20/min por IP (toda tentativa conta). Token expira em SANCTUM_EXPIRATION minutos (padrão 720).
         */
        post: operations["authLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout (revoga o token atual) */
        post: operations["authLogout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Usuário autenticado, colaborador vinculado e permissões */
        get: operations["authMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Troca a própria senha (revoga os demais tokens)
         * @description Política: mín. 10 caracteres, com maiúscula, minúscula e número. O token usado na requisição continua válido; todos os outros do usuário são revogados.
         */
        put: operations["authChangePassword"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Pede o link de redefinição de senha
         * @description Público. Sempre 200 com a mesma mensagem, exista ou não o e-mail (sem enumeração). Só usuário ativo e não excluído recebe o e-mail, enviado pela fila; o link é `${APP_FRONTEND_URL}/redefinir-senha#token=…&email=…` (fragmento: não vai ao servidor), vale 60 min e um pedido novo invalida o anterior. E-mail vazio ou malformado → 422. Rate limit: 3/min por e-mail + IP e 10/min por IP.
         */
        post: operations["authForgotPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Redefine a senha com o link recebido por e-mail
         * @description Público. Política de senha → 422 por campo (`password`, inclusive a confirmação). Link inválido, expirado, já usado, de outro e-mail ou de usuário inativo/excluído → 422 genérico em `errors.token`. Sucesso revoga todos os tokens de acesso do usuário e não faz login automático. Rate limit: 5/min por IP.
         */
        post: operations["authResetPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/branches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lista filiais
         * @description Permissão: branches.view (todos os perfis; sem escopo de filial). Ordenação: code, name, type, is_active, created_at, updated_at (`-` = desc; padrão code).
         */
        get: operations["branchesIndex"];
        put?: never;
        /**
         * Cria filial
         * @description Permissão: branches.manage. `code` duplicado entre registros ativos → 422.
         */
        post: operations["branchesStore"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/branches/{branch}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Detalha filial
         * @description Permissão: branches.view. Filial excluída → 404.
         */
        get: operations["branchesShow"];
        /**
         * Atualiza filial (parcial; PUT = PATCH)
         * @description Permissão: branches.manage. Só os campos enviados são validados e gravados.
         */
        put: operations["branchesUpdate"];
        post?: never;
        /**
         * Exclui filial (soft delete)
         * @description Permissão: branches.manage. 409 se houver centros de custo ou usuários ativos (não excluídos) vinculados; equipamentos e colaboradores entram nas F1-14/15.
         */
        delete: operations["branchesDestroy"];
        options?: never;
        head?: never;
        /** Atualiza filial (parcial; igual ao PUT) */
        patch: operations["branchesPatch"];
        trace?: never;
    };
    "/branches/{branch}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Restaura filial excluída
         * @description Permissão: branches.manage. 409 se não estiver excluída ou se o código já estiver em uso por uma filial ativa.
         */
        post: operations["branchesRestore"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cost-centers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lista centros de custo
         * @description Permissão: cost_centers.view (L e A). Escopo: não-admin vê os da própria filial + os sem filial. Ordenação: code, name, is_active, created_at, updated_at (`-` = desc; padrão code).
         */
        get: operations["costCentersIndex"];
        put?: never;
        /**
         * Cria centro de custo
         * @description Permissão: cost_centers.manage. `code` duplicado entre registros ativos → 422; filial inexistente ou excluída → 422.
         */
        post: operations["costCentersStore"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cost-centers/{cost_center}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Detalha centro de custo
         * @description Permissão: cost_centers.view. Excluído ou fora do escopo de filial → 404.
         */
        get: operations["costCentersShow"];
        /**
         * Atualiza centro de custo (parcial; PUT = PATCH)
         * @description Permissão: cost_centers.manage. Só os campos enviados são validados e gravados. Trocar a filial com colaboradores de outra filial vinculados → 422.
         */
        put: operations["costCentersUpdate"];
        post?: never;
        /**
         * Exclui centro de custo (soft delete)
         * @description Permissão: cost_centers.manage. 409 se houver equipamentos ou colaboradores ativos vinculados (regras ativadas nas F1-14/15).
         */
        delete: operations["costCentersDestroy"];
        options?: never;
        head?: never;
        /** Atualiza centro de custo (parcial; igual ao PUT) */
        patch: operations["costCentersPatch"];
        trace?: never;
    };
    "/cost-centers/{cost_center}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Restaura centro de custo excluído
         * @description Permissão: cost_centers.manage. 409 se não estiver excluído, se o código já estiver em uso por um centro de custo ativo ou se a filial vinculada estiver excluída.
         */
        post: operations["costCentersRestore"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/employees": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lista colaboradores
         * @description Permissão: employees.view (L e A). Escopo: L vê só a própria filial. Busca `q` em name e registration. Ordenação: name, registration, job_type, hired_at (`-` = desc; padrão name).
         */
        get: operations["employeesIndex"];
        put?: never;
        /**
         * Cria colaborador
         * @description Permissão: employees.manage. 422: matrícula duplicada entre ativos; filial/centro de custo inexistente ou excluído; centro de custo de outra filial; usuário excluído, já vinculado ou (não-admin) de outra filial; campo fora do job_type.
         */
        post: operations["employeesStore"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/employees/{employee}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Detalha colaborador
         * @description Permissão: employees.view. Excluído ou de outra filial (L) → 404.
         */
        get: operations["employeesShow"];
        /**
         * Atualiza colaborador (parcial; PUT = PATCH)
         * @description Permissão: employees.manage. Só os campos enviados são validados e gravados; as regras de filial valem também ao trocar a filial do colaborador.
         */
        put: operations["employeesUpdate"];
        post?: never;
        /**
         * Exclui colaborador (soft delete)
         * @description Permissão: employees.manage. 409 (`errors.dependents=["equipments"]`) se for responsável por equipamento ativo, regra ativada na F1-15. O usuário vinculado fica livre.
         */
        delete: operations["employeesDestroy"];
        options?: never;
        head?: never;
        /** Atualiza colaborador (parcial; igual ao PUT) */
        patch: operations["employeesPatch"];
        trace?: never;
    };
    "/employees/{employee}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Restaura colaborador excluído
         * @description Permissão: employees.manage. 409 se não estiver excluído, se a matrícula foi reutilizada, se o usuário vinculado está excluído, já vinculado a outro colaborador ou (não-admin) em outra filial, ou se a filial ou o centro de custo vinculado está excluído (ou o centro de custo mudou para outra filial).
         */
        post: operations["employeesRestore"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/equipment-families": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lista famílias de equipamento
         * @description Permissão: equipment_families.view (M, L e A; sem escopo de filial). Busca `q` em code e name. Ordenação: code, name, category, criticality (`-` = desc; padrão code); outro campo → 422.
         */
        get: operations["equipmentFamiliesIndex"];
        put?: never;
        /**
         * Cria família de equipamento
         * @description Permissão: equipment_families.manage. `code` duplicado entre registros ativos → 422; preventive_lead_pct fora de (0, 100] ou tolerância negativa → 422.
         */
        post: operations["equipmentFamiliesStore"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/equipment-families/{equipment_family}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Detalha família de equipamento
         * @description Permissão: equipment_families.view. Família excluída → 404.
         */
        get: operations["equipmentFamiliesShow"];
        /**
         * Atualiza família de equipamento (parcial; PUT = PATCH)
         * @description Permissão: equipment_families.manage. Só os campos enviados são validados e gravados.
         */
        put: operations["equipmentFamiliesUpdate"];
        post?: never;
        /**
         * Exclui família de equipamento (soft delete)
         * @description Permissão: equipment_families.manage. 409 (`errors.dependents=["equipments"]`) se houver equipamentos ativos, regra ativada na F1-15. Exclusão concorrente de família já excluída → 404.
         */
        delete: operations["equipmentFamiliesDestroy"];
        options?: never;
        head?: never;
        /** Atualiza família de equipamento (parcial; igual ao PUT) */
        patch: operations["equipmentFamiliesPatch"];
        trace?: never;
    };
    "/equipment-families/{equipment_family}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Restaura família de equipamento excluída
         * @description Permissão: equipment_families.manage. 409 se não estiver excluída ou se o código já estiver em uso por uma família ativa.
         */
        post: operations["equipmentFamiliesRestore"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Saúde da aplicação (db e redis)
         * @description Público e fora do rate limit. 503 se db ou redis estiverem fora (o corpo traz o estado de cada componente em `data`).
         */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/meta/enums": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Enums e metadados para selects
         * @description Enums para selects; cresce com os cadastros. Perfil: qualquer autenticado.
         */
        get: operations["metaEnums"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lista usuários
         * @description Permissão: users.view (A). Sem escopo de filial. Busca `q` em name, username e email. Ordenação: name, username, email, role, created_at, last_login_at (`-` = desc; padrão name).
         */
        get: operations["usersIndex"];
        put?: never;
        /**
         * Cria usuário
         * @description Permissão: users.manage. E-mail duplicado entre usuários ativos → 422; perfil não-admin sem `branch_id` → 422; filial inexistente ou excluída → 422.
         */
        post: operations["usersStore"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{user}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Detalha usuário
         * @description Permissão: users.view. Usuário excluído → 404.
         */
        get: operations["usersShow"];
        /**
         * Atualiza usuário (parcial; PUT = PATCH)
         * @description Permissão: users.manage. Só os campos enviados são validados e gravados. Usuário vinculado a colaborador: não-admin precisa ficar na filial do colaborador (422 ao mudar branch_id ou rebaixar de admin). Revoga todos os tokens do usuário ao trocar a senha de outro usuário ou ao desativá-lo (na própria senha, revoga os demais tokens). 409: alterar o próprio perfil, desativar a si mesmo, rebaixar ou desativar o último admin ativo.
         */
        put: operations["usersUpdate"];
        post?: never;
        /**
         * Exclui usuário (soft delete)
         * @description Permissão: users.manage. Revoga todos os tokens do usuário. 409: excluir a si mesmo, o último admin ativo ou usuário com colaborador vinculado não excluído (`errors.dependents=["employees"]`).
         */
        delete: operations["usersDestroy"];
        options?: never;
        head?: never;
        /** Atualiza usuário (parcial; igual ao PUT) */
        patch: operations["usersPatch"];
        trace?: never;
    };
    "/users/{user}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Restaura usuário excluído
         * @description Permissão: users.manage. 409 se não estiver excluído, se o e-mail ou o username já estiver em uso por um usuário ativo ou se a filial vinculada estiver excluída. Os tokens revogados na exclusão não voltam.
         */
        post: operations["usersRestore"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AuditLogEnvelope: components["schemas"]["Envelope"] & {
            data?: components["schemas"]["AuditLog"];
        };
        LoginData: {
            /** @example 1|9fQk... */
            token: string;
            /** @enum {string} */
            token_type: "Bearer";
            /**
             * Format: date-time
             * @example 2026-10-09T02:03:22.123456Z
             */
            expires_at: string;
            user: components["schemas"]["AuthUser"];
        };
        MeData: {
            user: components["schemas"]["AuthUser"];
            /** @description Colaborador vinculado ao usuário (1:1); null quando não há. */
            employee: {
                /** @example 1 */
                id: number;
                /** @example MAT-00123 */
                registration: string;
                /** @example João Pereira */
                name: string;
                /** @enum {string} */
                job_type: "driver" | "mechanic" | "leader" | "admin_staff";
                /** @example 1 */
                branch_id: number;
            } | null;
            /**
             * @description Permissões do perfil (config/rbac.php). auth.* é implícito e não aparece.
             * @example [
             *       "branches.view",
             *       "equipments.view"
             *     ]
             */
            permissions: string[];
        };
        /** @description Create: code, name e type obrigatórios. Update (PUT = PATCH): parcial, só os campos enviados. `code` é gravado sem espaços nas pontas e em maiúsculas; `state` em maiúsculas. */
        BranchInput: {
            /** @example FIL-001 */
            code?: string;
            /** @example Matriz */
            name?: string;
            /** @enum {string} */
            type?: "filial" | "garagem" | "oficina";
            city?: string | null;
            /** @enum {string|null} */
            state?: "AC" | "AL" | "AP" | "AM" | "BA" | "CE" | "DF" | "ES" | "GO" | "MA" | "MT" | "MS" | "MG" | "PA" | "PB" | "PR" | "PE" | "PI" | "RJ" | "RN" | "RS" | "RO" | "RR" | "SC" | "SP" | "SE" | "TO" | null;
            /** @default true */
            is_active: boolean;
        };
        BranchEnvelope: components["schemas"]["Envelope"] & {
            data?: components["schemas"]["Branch"];
        };
        /** @description Create: code e name obrigatórios. Update (PUT = PATCH): parcial. `code` é gravado sem espaços nas pontas e em maiúsculas. `branch_id` deve ser filial existente e não excluída (inativa é aceita); null = sem filial. */
        CostCenterInput: {
            /** @example CC-0101 */
            code?: string;
            /** @example Manutenção pesada */
            name?: string;
            /** @example 1 */
            branch_id?: number | null;
            /** @default true */
            is_active: boolean;
        };
        CostCenterEnvelope: components["schemas"]["Envelope"] & {
            data?: components["schemas"]["CostCenter"];
        };
        /** @description Create: registration, name, job_type e branch_id obrigatórios. Update (PUT = PATCH): parcial. `registration` é gravada sem espaços nas pontas e em maiúsculas (única entre não excluídos). Campos de CNH só para `driver`; `specialty` e `hourly_cost` só para `mechanic` (valor em campo de outro tipo → 422). Ao trocar o `job_type`, os campos preenchidos do tipo anterior precisam vir como null no mesmo payload (senão 422). `cost_center_id`: não excluído e da mesma filial do colaborador ou sem filial. `user_id`: usuário não excluído e livre; se não for admin, precisa ser da mesma filial do colaborador. */
        EmployeeInput: {
            /** @example MAT-00123 */
            registration?: string;
            /** @example João Pereira */
            name?: string;
            /** @enum {string} */
            job_type?: "driver" | "mechanic" | "leader" | "admin_staff";
            /** @example 1 */
            branch_id?: number;
            cost_center_id?: number | null;
            user_id?: number | null;
            phone?: string | null;
            /** Format: date */
            hired_at?: string | null;
            cnh_number?: string | null;
            /** @enum {string|null} */
            cnh_category?: "A" | "B" | "C" | "D" | "E" | "AB" | "AC" | "AD" | "AE" | null;
            /** Format: date */
            cnh_expires_at?: string | null;
            specialty?: string | null;
            /**
             * Format: float
             * @example 85.5
             */
            hourly_cost?: number | null;
            /** @default true */
            is_active: boolean;
        };
        EmployeeEnvelope: components["schemas"]["Envelope"] & {
            data?: components["schemas"]["Employee"];
        };
        /** @description Create: code, name e category obrigatórios; criticality (padrão medium) e preventive_lead_pct (padrão 90) opcionais. Update (PUT = PATCH): parcial. `code` é gravado sem espaços nas pontas e em maiúsculas. `preventive_lead_pct` em (0, 100] com até 2 casas; tolerâncias inteiras ≥ 0 ou null. */
        EquipmentFamilyInput: {
            /** @example CAM-PESADO */
            code?: string;
            /** @example Caminhões pesados */
            name?: string;
            /** @enum {string} */
            category?: "light_vehicle" | "truck" | "agri_machine" | "implement" | "support";
            /**
             * @default medium
             * @enum {string}
             */
            criticality: "low" | "medium" | "high" | "critical";
            /**
             * Format: float
             * @default 90
             * @example 87.5
             */
            preventive_lead_pct: number;
            /** @example 500 */
            tolerance_km?: number | null;
            /** @example 20 */
            tolerance_hours?: number | null;
            /** @example 7 */
            tolerance_days?: number | null;
            /** @default true */
            is_active: boolean;
        };
        EquipmentFamilyEnvelope: components["schemas"]["Envelope"] & {
            data?: components["schemas"]["EquipmentFamily"];
        };
        HealthData: {
            /** @enum {string} */
            app: "up";
            /** @enum {string} */
            db: "up" | "down";
            /** @enum {string} */
            redis: "up" | "down";
            /** @example 0.1.0 */
            version: string;
        };
        /** @description Create: name, username, email, password e role obrigatórios. Update (PUT = PATCH): parcial. `username`: trim + minúsculas e depois letras minúsculas sem acento, números e ponto (não no início, no fim nem repetido), 3 a 30 caracteres; fora disso (acento, espaço, `_`, `-`, `@`, `..`) → 422, sem transliteração; único entre não excluídos. `email` é gravado em minúsculas e é único entre usuários não excluídos. `password`: mín. 10 caracteres, com maiúscula, minúscula e número. `branch_id` é obrigatório quando o perfil (enviado ou atual) não é admin, inclusive ao trocar de admin para outro perfil; filial existente e não excluída (inativa é aceita). */
        UserInput: {
            /** @example Ana Souza */
            name?: string;
            /** @example ana.souza */
            username?: string;
            /**
             * Format: email
             * @example ana@example.com
             */
            email?: string;
            /** Format: password */
            password?: string;
            /** @enum {string} */
            role?: "operator" | "mechanic" | "leader" | "admin";
            /** @example 1 */
            branch_id?: number | null;
            /** @default true */
            is_active: boolean;
        };
        UserEnvelope: components["schemas"]["Envelope"] & {
            data?: components["schemas"]["User"];
        };
        AuditLog: {
            /**
             * @description Item de /audit-logs no formato da F.1. `actor` vem do snapshot gravado no evento (nome/perfil na
             *     época), null em ações do sistema; `auditable.type` é o alias curto (AuditLog::AUDITABLE_TYPES).
             * @example 1
             */
            id: number;
            /** Format: uuid */
            uuid: string;
            /**
             * Format: date-time
             * @description UTC com microssegundos.
             * @example 2026-10-08T14:03:22.123456Z
             */
            event_at: string;
            /** @description Quem executou (snapshot da época); null = sistema ou login_failed. */
            actor: {
                /** @example 1 */
                id: number;
                /** @example Ana Souza */
                name: string | null;
                /** @enum {string|null} */
                role: "operator" | "mechanic" | "leader" | "admin" | null;
            } | null;
            /** @enum {string} */
            action: "created" | "updated" | "deleted" | "restored" | "login_succeeded" | "login_failed" | "logout" | "password_changed" | "password_reset_requested" | "password_reset" | "setting_changed" | "setting_removed";
            /** @description Registro afetado; null em eventos sem alvo (ex.: login_failed). */
            auditable: {
                /** @example cost_center */
                type: string;
                /** @example 1 */
                id: number | null;
            } | null;
            /** @description Valores anteriores (só campos alterados em updated); sem dados sensíveis. */
            old_values: {
                [key: string]: unknown;
            } | null;
            new_values: {
                [key: string]: unknown;
            } | null;
            metadata: {
                [key: string]: unknown;
            } | null;
            /** @example 172.18.0.1 */
            ip: string | null;
            /** Format: uuid */
            request_id: string | null;
        };
        Branch: {
            /** @example 1 */
            id: number;
            /** @example FIL-001 */
            code: string;
            /** @example Matriz */
            name: string;
            /** @enum {string} */
            type: "filial" | "garagem" | "oficina";
            /** @example Goiânia */
            city: string | null;
            /**
             * @example GO
             * @enum {string|null}
             */
            state: "AC" | "AL" | "AP" | "AM" | "BA" | "CE" | "DF" | "ES" | "GO" | "MA" | "MT" | "MS" | "MG" | "PA" | "PB" | "PR" | "PE" | "PI" | "RJ" | "RN" | "RS" | "RO" | "RR" | "SC" | "SP" | "SE" | "TO" | null;
            is_active: boolean;
            /** Format: date-time */
            created_at: string | null;
            /** Format: date-time */
            updated_at: string | null;
            /**
             * Format: date-time
             * @description Sempre presente; null quando ativo.
             */
            deleted_at: string | null;
        };
        CostCenter: {
            /** @example 1 */
            id: number;
            /** @example CC-0101 */
            code: string;
            /** @example Manutenção pesada */
            name: string;
            /** @description Filial `{id, code, name}`; null = sem filial (visível a todas). */
            branch: {
                /** @example 1 */
                id: number;
                /** @example FIL-001 */
                code: string;
                /** @example Matriz */
                name: string;
            } | null;
            is_active: boolean;
            /** Format: date-time */
            created_at: string | null;
            /** Format: date-time */
            updated_at: string | null;
            /**
             * Format: date-time
             * @description Sempre presente; null quando ativo.
             */
            deleted_at: string | null;
        };
        Employee: {
            /** @example 1 */
            id: number;
            /**
             * @description Matrícula (maiúsculas).
             * @example MAT-00123
             */
            registration: string;
            /** @example João Pereira */
            name: string;
            /** @enum {string} */
            job_type: "driver" | "mechanic" | "leader" | "admin_staff";
            branch: {
                /** @example 1 */
                id: number;
                /** @example FIL-001 */
                code: string;
                /** @example Matriz */
                name: string;
            };
            cost_center: {
                /** @example 1 */
                id: number;
                /** @example CC-0101 */
                code: string;
                /** @example Manutenção pesada */
                name: string;
            } | null;
            /** @description Usuário vinculado (1:1); null = sem acesso ao sistema. */
            user: {
                /** @example 1 */
                id: number;
                /** @example João Pereira */
                name: string;
                /**
                 * Format: email
                 * @example joao@example.com
                 */
                email: string;
            } | null;
            phone: string | null;
            /** Format: date */
            hired_at: string | null;
            /** @description Só motorista. */
            cnh_number: string | null;
            /**
             * @description Só motorista.
             * @enum {string|null}
             */
            cnh_category: "A" | "B" | "C" | "D" | "E" | "AB" | "AC" | "AD" | "AE" | null;
            /**
             * Format: date
             * @description Só motorista.
             */
            cnh_expires_at: string | null;
            /** @description Só mecânico. */
            specialty: string | null;
            /**
             * Format: float
             * @description Só mecânico. Custo/hora; número JSON, até 2 casas.
             * @example 85.5
             */
            hourly_cost: number | null;
            is_active: boolean;
            /** Format: date-time */
            created_at: string | null;
            /** Format: date-time */
            updated_at: string | null;
            /**
             * Format: date-time
             * @description Sempre presente; null quando ativo.
             */
            deleted_at: string | null;
        };
        EquipmentFamily: {
            /** @example 1 */
            id: number;
            /** @example CAM-PESADO */
            code: string;
            /** @example Caminhões pesados */
            name: string;
            /** @enum {string} */
            category: "light_vehicle" | "truck" | "agri_machine" | "implement" | "support";
            /** @enum {string} */
            criticality: "low" | "medium" | "high" | "critical";
            /**
             * Format: float
             * @description Margem de antecedência do pré-alerta (RN-001), em %. Número JSON, até 2 casas.
             * @example 87.5
             */
            preventive_lead_pct: number;
            tolerance_km: number | null;
            tolerance_hours: number | null;
            tolerance_days: number | null;
            is_active: boolean;
            /** Format: date-time */
            created_at: string | null;
            /** Format: date-time */
            updated_at: string | null;
            /**
             * Format: date-time
             * @description Sempre presente; null quando ativo.
             */
            deleted_at: string | null;
        };
        User: {
            /**
             * @description Usuário no CRUD /users (contrato v1.3). Nunca inclui `password` nem `remember_token`.
             *     O usuário de /auth/* usa UserResource (schema AuthUser).
             * @example 1
             */
            id: number;
            /** @example Ana Souza */
            name: string;
            /**
             * @description Minúsculas sem acento, números e ponto (não no início, no fim nem repetido), 3 a 30.
             * @example ana.souza
             */
            username: string;
            /**
             * Format: email
             * @example ana@example.com
             */
            email: string;
            /** @enum {string} */
            role: "operator" | "mechanic" | "leader" | "admin";
            /** @description Filial `{id, code, name}`; null = todas (somente admin). */
            branch: {
                /** @example 1 */
                id: number;
                /** @example FIL-001 */
                code: string;
                /** @example Matriz */
                name: string;
            } | null;
            is_active: boolean;
            /** Format: date-time */
            last_login_at: string | null;
            /** Format: date-time */
            created_at: string | null;
            /** Format: date-time */
            updated_at: string | null;
            /**
             * Format: date-time
             * @description Sempre presente; null quando ativo.
             */
            deleted_at: string | null;
        };
        AuthUser: {
            /** @example 1 */
            id: number;
            /** @example Ana Souza */
            name: string;
            /**
             * @description Minúsculas sem acento, números e ponto (não no início, no fim nem repetido), 3 a 30.
             * @example ana.souza
             */
            username: string;
            /**
             * Format: email
             * @example ana@example.com
             */
            email: string;
            /** @enum {string} */
            role: "operator" | "mechanic" | "leader" | "admin";
            /** @description Filial do usuário; null = todas (somente admin). */
            branch: {
                /** @example 1 */
                id: number;
                /** @example FIL-001 */
                code: string;
                /** @example Matriz */
                name: string;
            } | null;
        };
        /** @description Envelope padrão de toda resposta. */
        Envelope: {
            /**
             * @description Definições globais da OpenAPI (info, servidor, segurança, schemas e respostas reutilizáveis).
             *     Os endpoints são anotados nos próprios controllers. O atributo não aceita expressão, então
             *     título e descrição usam os marcadores de OpenApiBuilder::BRAND_TOKENS, preenchidos com a
             *     marca do config (app.name / app.full_name) na geração.
             * @enum {string}
             */
            status: "success" | "error";
            /** @example Operação realizada com sucesso. */
            message: string;
            errors: {
                [key: string]: string[];
            } | null;
            /** @description Objeto, lista ou null conforme o endpoint (qualquer tipo). */
            data: unknown;
            meta?: components["schemas"]["Pagination"];
        };
        /** @description Presente (`meta`) apenas em listas paginadas. */
        Pagination: {
            /** @example 1 */
            current_page: number;
            /** @example 15 */
            per_page: number;
            /** @example 0 */
            total: number;
            /** @example 1 */
            last_page: number;
        };
        /** @description Resposta de erro (401, 403, 404, 405, 409, 429, 500, 503). */
        ErrorEnvelope: {
            /** @enum {string} */
            status: "error";
            /** @example Recurso não encontrado. */
            message: string;
            /** @example null */
            errors: Record<string, never> | null;
            /**
             * @description Sempre null em erros.
             * @example null
             */
            data: unknown;
        };
        /** @description Erro de validação (422): `errors` mapeia campo → mensagens. */
        ValidationErrorEnvelope: {
            /** @enum {string} */
            status: "error";
            /** @example Os dados informados são inválidos. */
            message: string;
            /**
             * @example {
             *       "email": [
             *         "O campo email é obrigatório."
             *       ]
             *     }
             */
            errors: {
                [key: string]: string[];
            };
            /**
             * @description Sempre null em erros.
             * @example null
             */
            data: unknown;
        };
        /** @description Exclusão bloqueada por dependentes ativos (409): `errors.dependents` lista os tipos. */
        DeleteConflictEnvelope: {
            /** @enum {string} */
            status: "error";
            /** @example Não é possível excluir: existem registros ativos vinculados (centros de custo). */
            message: string;
            /**
             * @example {
             *       "dependents": [
             *         "cost_centers"
             *       ]
             *     }
             */
            errors: {
                [key: string]: string[];
            } | null;
            /** @example null */
            data: unknown;
        };
    };
    responses: {
        /** @description Não autenticado (401). */
        Unauthenticated: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Acesso negado (403). */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Recurso não encontrado (404). */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Conflito de regra de negócio (409). */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Dados inválidos (422). */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ValidationErrorEnvelope"];
            };
        };
        /** @description Limite de requisições excedido (429). */
        TooManyRequests: {
            headers: {
                /** @description Segundos até poder tentar novamente. */
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Erro interno (500), sem detalhes técnicos com APP_DEBUG=false. */
        ServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: {
        /** @description Página (1..n). */
        Page: number;
        /** @description Itens por página: máx. 100; até 200 com `is_active=1` (selects). */
        PerPage: number;
        /** @description Busca textual (contém, sem diferenciar maiúsculas; `%` e `_` são literais). */
        Search: string;
        /** @description Inclui registros excluídos (soft delete). Exige `*.manage` do recurso; sem ela → 403. */
        WithTrashed: 0 | 1;
        /** @description Filtra por ativo (1) / inativo (0). */
        IsActive: 0 | 1;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    auditLogsIndex: {
        parameters: {
            query?: {
                /** @description Página (1..n). */
                page?: components["parameters"]["Page"];
                /** @description Itens por página: máx. 100; até 200 com `is_active=1` (selects). */
                per_page?: components["parameters"]["PerPage"];
                /** @description Alias curto do registro auditado; desconhecido → 422. */
                auditable_type?: "branch" | "cost_center" | "employee" | "equipment_family" | "user";
                auditable_id?: number;
                actor_id?: number;
                action?: "created" | "updated" | "deleted" | "restored" | "login_succeeded" | "login_failed" | "logout" | "password_changed" | "password_reset_requested" | "password_reset" | "setting_changed" | "setting_removed";
                /** @description ISO 8601 (date-time ou só a data, dia inteiro em UTC); inclusivo. */
                from?: string;
                /** @description ISO 8601 (date-time ou só a data, até 23:59:59.999999 UTC); inclusivo; menor que `from` → 422. */
                to?: string;
                request_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista paginada. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["AuditLog"][];
                    };
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationError"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    auditLogsShow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                audit_log: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Evento. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditLogEnvelope"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    authLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @description Nome de usuário (trim + minúsculas no servidor).
                     * @example admin
                     */
                    username: string;
                    /** Format: password */
                    password: string;
                    /** @example web */
                    device_name: string;
                };
            };
        };
        responses: {
            /** @description Autenticado. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["LoginData"];
                    };
                };
            };
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationError"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["ServerError"];
        };
    };
    authLogout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Token revogado (`data` null). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["ServerError"];
        };
    };
    authMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dados da sessão. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["MeData"];
                    };
                };
            };
            401: components["responses"]["Unauthenticated"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["ServerError"];
        };
    };
    authChangePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: password */
                    current_password: string;
                    /** Format: password */
                    password: string;
                    /** Format: password */
                    password_confirmation: string;
                };
            };
        };
        responses: {
            /** @description Senha alterada (`data` null). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            422: components["responses"]["ValidationError"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["ServerError"];
        };
    };
    authForgotPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * Format: email
                     * @example ana@example.com
                     */
                    email: string;
                };
            };
        };
        responses: {
            /** @description Mensagem genérica (`data` null). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            422: components["responses"]["ValidationError"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["ServerError"];
        };
    };
    authResetPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                    /** @description Token do link do e-mail. */
                    token: string;
                    /** Format: password */
                    password: string;
                    /** Format: password */
                    password_confirmation: string;
                };
            };
        };
        responses: {
            /** @description Senha redefinida (`data` null). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            422: components["responses"]["ValidationError"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["ServerError"];
        };
    };
    branchesIndex: {
        parameters: {
            query?: {
                /** @description Página (1..n). */
                page?: components["parameters"]["Page"];
                /** @description Itens por página: máx. 100; até 200 com `is_active=1` (selects). */
                per_page?: components["parameters"]["PerPage"];
                /** @description Busca textual (contém, sem diferenciar maiúsculas; `%` e `_` são literais). */
                q?: components["parameters"]["Search"];
                sort?: string;
                type?: "filial" | "garagem" | "oficina";
                /** @description Filtra por ativo (1) / inativo (0). */
                is_active?: components["parameters"]["IsActive"];
                /** @description Inclui registros excluídos (soft delete). Exige `*.manage` do recurso; sem ela → 403. */
                with_trashed?: components["parameters"]["WithTrashed"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista paginada. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["Branch"][];
                    };
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationError"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    branchesStore: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BranchInput"];
            };
        };
        responses: {
            /** @description Criada. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BranchEnvelope"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationError"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    branchesShow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                branch: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Filial. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BranchEnvelope"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    branchesUpdate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                branch: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BranchInput"];
            };
        };
        responses: {
            /** @description Atualizada. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BranchEnvelope"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationError"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    branchesDestroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                branch: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Excluída (`data` null). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description Dependentes ativos. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteConflictEnvelope"];
                };
            };
            429: components["responses"]["TooManyRequests"];
        };
    };
    branchesPatch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                branch: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BranchInput"];
            };
        };
        responses: {
            /** @description Atualizada. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BranchEnvelope"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationError"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    branchesRestore: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                branch: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Restaurada. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BranchEnvelope"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    costCentersIndex: {
        parameters: {
            query?: {
                /** @description Página (1..n). */
                page?: components["parameters"]["Page"];
                /** @description Itens por página: máx. 100; até 200 com `is_active=1` (selects). */
                per_page?: components["parameters"]["PerPage"];
                /** @description Busca textual (contém, sem diferenciar maiúsculas; `%` e `_` são literais). */
                q?: components["parameters"]["Search"];
                sort?: string;
                branch_id?: number;
                /** @description Filtra por ativo (1) / inativo (0). */
                is_active?: components["parameters"]["IsActive"];
                /** @description Inclui registros excluídos (soft delete). Exige `*.manage` do recurso; sem ela → 403. */
                with_trashed?: components["parameters"]["WithTrashed"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista paginada. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["CostCenter"][];
                    };
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationError"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    costCentersStore: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CostCenterInput"];
            };
        };
        responses: {
            /** @description Criada. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CostCenterEnvelope"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationError"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    costCentersShow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cost_center: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Filial. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CostCenterEnvelope"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    costCentersUpdate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cost_center: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CostCenterInput"];
            };
        };
        responses: {
            /** @description Atualizada. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CostCenterEnvelope"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationError"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    costCentersDestroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cost_center: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Excluída (`data` null). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description Dependentes ativos. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteConflictEnvelope"];
                };
            };
            429: components["responses"]["TooManyRequests"];
        };
    };
    costCentersPatch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cost_center: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CostCenterInput"];
            };
        };
        responses: {
            /** @description Atualizada. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CostCenterEnvelope"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationError"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    costCentersRestore: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cost_center: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Restaurada. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CostCenterEnvelope"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    employeesIndex: {
        parameters: {
            query?: {
                /** @description Página (1..n). */
                page?: components["parameters"]["Page"];
                /** @description Itens por página: máx. 100; até 200 com `is_active=1` (selects). */
                per_page?: components["parameters"]["PerPage"];
                /** @description Busca textual (contém, sem diferenciar maiúsculas; `%` e `_` são literais). */
                q?: components["parameters"]["Search"];
                sort?: string;
                job_type?: "driver" | "mechanic" | "leader" | "admin_staff";
                branch_id?: number;
                /** @description Filtra por ativo (1) / inativo (0). */
                is_active?: components["parameters"]["IsActive"];
                /** @description Inclui registros excluídos (soft delete). Exige `*.manage` do recurso; sem ela → 403. */
                with_trashed?: components["parameters"]["WithTrashed"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista paginada. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["Employee"][];
                    };
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationError"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    employeesStore: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmployeeInput"];
            };
        };
        responses: {
            /** @description Criado. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployeeEnvelope"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationError"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    employeesShow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                employee: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Colaborador. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployeeEnvelope"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    employeesUpdate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                employee: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmployeeInput"];
            };
        };
        responses: {
            /** @description Atualizado. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployeeEnvelope"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationError"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    employeesDestroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                employee: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Excluído (`data` null). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description Dependentes ativos. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteConflictEnvelope"];
                };
            };
            429: components["responses"]["TooManyRequests"];
        };
    };
    employeesPatch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                employee: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmployeeInput"];
            };
        };
        responses: {
            /** @description Atualizado. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployeeEnvelope"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationError"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    employeesRestore: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                employee: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Restaurado. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployeeEnvelope"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    equipmentFamiliesIndex: {
        parameters: {
            query?: {
                /** @description Página (1..n). */
                page?: components["parameters"]["Page"];
                /** @description Itens por página: máx. 100; até 200 com `is_active=1` (selects). */
                per_page?: components["parameters"]["PerPage"];
                /** @description Busca textual (contém, sem diferenciar maiúsculas; `%` e `_` são literais). */
                q?: components["parameters"]["Search"];
                sort?: string;
                category?: "light_vehicle" | "truck" | "agri_machine" | "implement" | "support";
                criticality?: "low" | "medium" | "high" | "critical";
                /** @description Filtra por ativo (1) / inativo (0). */
                is_active?: components["parameters"]["IsActive"];
                /** @description Inclui registros excluídos (soft delete). Exige `*.manage` do recurso; sem ela → 403. */
                with_trashed?: components["parameters"]["WithTrashed"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista paginada. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["EquipmentFamily"][];
                    };
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationError"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    equipmentFamiliesStore: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EquipmentFamilyInput"];
            };
        };
        responses: {
            /** @description Criada (criticality=medium e preventive_lead_pct=90 quando omitidos). */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EquipmentFamilyEnvelope"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationError"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    equipmentFamiliesShow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                equipment_family: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Família. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EquipmentFamilyEnvelope"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    equipmentFamiliesUpdate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                equipment_family: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EquipmentFamilyInput"];
            };
        };
        responses: {
            /** @description Atualizada. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EquipmentFamilyEnvelope"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationError"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    equipmentFamiliesDestroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                equipment_family: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Excluída (`data` null). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description Dependentes ativos. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteConflictEnvelope"];
                };
            };
            429: components["responses"]["TooManyRequests"];
        };
    };
    equipmentFamiliesPatch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                equipment_family: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EquipmentFamilyInput"];
            };
        };
        responses: {
            /** @description Atualizada. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EquipmentFamilyEnvelope"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationError"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    equipmentFamiliesRestore: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                equipment_family: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Restaurada. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EquipmentFamilyEnvelope"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Todos os componentes ativos. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["HealthData"];
                    };
                };
            };
            /** @description Algum componente indisponível. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"] & {
                        data?: components["schemas"]["HealthData"];
                    };
                };
            };
        };
    };
    metaEnums: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Enums disponíveis. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: {
                            enums?: {
                                branch_types: ("filial" | "garagem" | "oficina")[];
                                roles: ("operator" | "mechanic" | "leader" | "admin")[];
                                equipment_categories: ("light_vehicle" | "truck" | "agri_machine" | "implement" | "support")[];
                                criticalities: ("low" | "medium" | "high" | "critical")[];
                                job_types: ("driver" | "mechanic" | "leader" | "admin_staff")[];
                                cnh_categories: ("A" | "B" | "C" | "D" | "E" | "AB" | "AC" | "AD" | "AE")[];
                            };
                        };
                    };
                };
            };
            401: components["responses"]["Unauthenticated"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["ServerError"];
        };
    };
    usersIndex: {
        parameters: {
            query?: {
                /** @description Página (1..n). */
                page?: components["parameters"]["Page"];
                /** @description Itens por página: máx. 100; até 200 com `is_active=1` (selects). */
                per_page?: components["parameters"]["PerPage"];
                /** @description Busca textual (contém, sem diferenciar maiúsculas; `%` e `_` são literais). */
                q?: components["parameters"]["Search"];
                sort?: string;
                role?: "operator" | "mechanic" | "leader" | "admin";
                branch_id?: number;
                /** @description Filtra por ativo (1) / inativo (0). */
                is_active?: components["parameters"]["IsActive"];
                /** @description Inclui registros excluídos (soft delete). Exige `*.manage` do recurso; sem ela → 403. */
                with_trashed?: components["parameters"]["WithTrashed"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista paginada. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["User"][];
                    };
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationError"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    usersStore: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserInput"];
            };
        };
        responses: {
            /** @description Criado. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserEnvelope"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationError"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    usersShow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Usuário. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserEnvelope"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    usersUpdate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserInput"];
            };
        };
        responses: {
            /** @description Atualizado. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserEnvelope"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    usersDestroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Excluído (`data` null). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    usersPatch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserInput"];
            };
        };
        responses: {
            /** @description Atualizado. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserEnvelope"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    usersRestore: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Restaurado. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserEnvelope"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            429: components["responses"]["TooManyRequests"];
        };
    };
}
