<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        DB::unprepared(<<<'SQL'
            CREATE TABLE branches (
                id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                code varchar(20) NOT NULL,
                name varchar(120) NOT NULL,
                type varchar(20) NOT NULL CHECK (type IN ('filial', 'garagem', 'oficina')),
                city varchar(80) NULL,
                state char(2) NULL,
                is_active boolean NOT NULL DEFAULT true,
                created_at timestamptz NULL,
                updated_at timestamptz NULL,
                deleted_at timestamptz NULL
            )
        SQL);

        // Unicidade só entre registros ativos (código de filial excluída pode ser reutilizado).
        DB::unprepared('CREATE UNIQUE INDEX branches_code_unique ON branches (code) WHERE deleted_at IS NULL');
    }

    public function down(): void
    {
        DB::unprepared('DROP TABLE IF EXISTS branches');
    }
};
