<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        DB::unprepared(<<<'SQL'
            CREATE TABLE cost_centers (
                id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                code varchar(30) NOT NULL,
                name varchar(120) NOT NULL,
                -- null = centro de custo sem filial (visível a todas)
                branch_id bigint NULL REFERENCES branches (id) ON DELETE RESTRICT,
                is_active boolean NOT NULL DEFAULT true,
                created_at timestamptz NULL,
                updated_at timestamptz NULL,
                deleted_at timestamptz NULL
            )
        SQL);

        DB::unprepared('CREATE UNIQUE INDEX cost_centers_code_unique ON cost_centers (code) WHERE deleted_at IS NULL');
        DB::unprepared('CREATE INDEX cost_centers_branch_id_idx ON cost_centers (branch_id)');
    }

    public function down(): void
    {
        DB::unprepared('DROP TABLE IF EXISTS cost_centers');
    }
};
