<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

/** Tabela padrão do Sanctum, com expires_at obrigatório (spec C.1). */
return new class extends Migration
{
    public function up(): void
    {
        DB::unprepared(<<<'SQL'
            CREATE TABLE personal_access_tokens (
                id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                tokenable_type varchar(255) NOT NULL,
                tokenable_id bigint NOT NULL,
                name text NOT NULL,
                token varchar(64) NOT NULL UNIQUE,
                abilities text NULL,
                last_used_at timestamptz NULL,
                expires_at timestamptz NOT NULL,
                created_at timestamptz NULL,
                updated_at timestamptz NULL
            )
        SQL);

        DB::unprepared('CREATE INDEX personal_access_tokens_tokenable_idx ON personal_access_tokens (tokenable_type, tokenable_id)');
        DB::unprepared('CREATE INDEX personal_access_tokens_expires_at_idx ON personal_access_tokens (expires_at)');
    }

    public function down(): void
    {
        DB::unprepared('DROP TABLE IF EXISTS personal_access_tokens');
    }
};
