<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        DB::unprepared(<<<'SQL'
            CREATE TABLE equipments (
                id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                code varchar(30) NOT NULL,
                name varchar(150) NOT NULL,
                family_id bigint NOT NULL REFERENCES equipment_families (id) ON DELETE RESTRICT,
                branch_id bigint NOT NULL REFERENCES branches (id) ON DELETE RESTRICT,
                -- obrigatório (herdado pela RN-005 no futuro)
                cost_center_id bigint NOT NULL REFERENCES cost_centers (id) ON DELETE RESTRICT,
                responsible_employee_id bigint NULL REFERENCES employees (id) ON DELETE RESTRICT,
                plate varchar(10) NULL,
                serial_number varchar(60) NULL,
                manufacturer varchar(80) NULL,
                model varchar(80) NULL,
                -- limite superior (ano atual + 1) no trigger abaixo: um CHECK com CURRENT_DATE não é imutável
                year smallint NULL CHECK (year >= 1950),
                status varchar(15) NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'inactive', 'disposed')),
                -- criticidade efetiva = override ?? família
                criticality_override varchar(10) NULL CHECK (criticality_override IN ('low', 'medium', 'high', 'critical')),
                -- valores iniciais/manuais (sem telemetria na Fase 1)
                odometer_km numeric(12,1) NOT NULL DEFAULT 0 CHECK (odometer_km >= 0),
                hour_meter numeric(12,1) NOT NULL DEFAULT 0 CHECK (hour_meter >= 0),
                acquisition_date date NULL,
                acquisition_value numeric(14,2) NULL CHECK (acquisition_value >= 0),
                notes text NULL,
                created_at timestamptz NULL,
                updated_at timestamptz NULL,
                deleted_at timestamptz NULL
            )
        SQL);

        DB::unprepared(<<<'SQL'
            CREATE OR REPLACE FUNCTION equipments_year_check() RETURNS trigger
            LANGUAGE plpgsql AS $$
            BEGIN
                IF NEW.year IS NOT NULL AND NEW.year > EXTRACT(YEAR FROM CURRENT_DATE)::int + 1 THEN
                    RAISE EXCEPTION 'equipments.year % fora de 1950..%', NEW.year, EXTRACT(YEAR FROM CURRENT_DATE)::int + 1
                        USING ERRCODE = 'check_violation';
                END IF;
                RETURN NEW;
            END;
            $$;
            CREATE TRIGGER equipments_year_check BEFORE INSERT OR UPDATE OF year ON equipments
                FOR EACH ROW EXECUTE FUNCTION equipments_year_check();
        SQL);

        DB::unprepared('CREATE UNIQUE INDEX equipments_code_unique ON equipments (code) WHERE deleted_at IS NULL');
        DB::unprepared('CREATE UNIQUE INDEX equipments_plate_unique ON equipments (plate) WHERE deleted_at IS NULL AND plate IS NOT NULL');
        DB::unprepared('CREATE INDEX equipments_family_id_idx ON equipments (family_id)');
        DB::unprepared('CREATE INDEX equipments_branch_id_idx ON equipments (branch_id)');
        DB::unprepared('CREATE INDEX equipments_cost_center_id_idx ON equipments (cost_center_id)');
        DB::unprepared('CREATE INDEX equipments_status_idx ON equipments (status)');
        DB::unprepared('CREATE INDEX equipments_responsible_employee_id_idx ON equipments (responsible_employee_id)');
        DB::unprepared('CREATE INDEX equipments_branch_id_status_idx ON equipments (branch_id, status)');
    }

    public function down(): void
    {
        DB::unprepared('DROP TABLE IF EXISTS equipments');
        DB::unprepared('DROP FUNCTION IF EXISTS equipments_year_check()');
    }
};
