<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        DB::unprepared(<<<'SQL'
            CREATE TABLE employees (
                id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                -- vínculo 1:1 opcional com o usuário (único entre não excluídos)
                user_id bigint NULL REFERENCES users (id) ON DELETE RESTRICT,
                registration varchar(30) NOT NULL,
                name varchar(120) NOT NULL,
                job_type varchar(20) NOT NULL CHECK (job_type IN ('driver', 'mechanic', 'leader', 'admin_staff')),
                branch_id bigint NOT NULL REFERENCES branches (id) ON DELETE RESTRICT,
                cost_center_id bigint NULL REFERENCES cost_centers (id) ON DELETE RESTRICT,
                phone varchar(30) NULL,
                hired_at date NULL,
                -- motorista
                cnh_number varchar(20) NULL,
                cnh_category varchar(3) NULL CHECK (cnh_category IN ('A', 'B', 'C', 'D', 'E', 'AB', 'AC', 'AD', 'AE')),
                cnh_expires_at date NULL,
                -- mecânico
                specialty varchar(80) NULL,
                hourly_cost numeric(10,2) NULL CHECK (hourly_cost >= 0),
                is_active boolean NOT NULL DEFAULT true,
                created_at timestamptz NULL,
                updated_at timestamptz NULL,
                deleted_at timestamptz NULL
            )
        SQL);

        DB::unprepared('CREATE UNIQUE INDEX employees_registration_unique ON employees (registration) WHERE deleted_at IS NULL');
        DB::unprepared('CREATE UNIQUE INDEX employees_user_id_unique ON employees (user_id) WHERE deleted_at IS NULL AND user_id IS NOT NULL');
        DB::unprepared('CREATE INDEX employees_branch_id_idx ON employees (branch_id)');
        DB::unprepared('CREATE INDEX employees_job_type_idx ON employees (job_type)');
        DB::unprepared('CREATE INDEX employees_cost_center_id_idx ON employees (cost_center_id)');
    }

    public function down(): void
    {
        DB::unprepared('DROP TABLE IF EXISTS employees');
    }
};
