<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        DB::unprepared(<<<'SQL'
            CREATE TABLE settings (
                id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                key varchar(100) NOT NULL,
                scope_type varchar(10) NOT NULL CHECK (scope_type IN ('global', 'branch', 'family')),
                -- branches.id ou equipment_families.id conforme scope_type (validado na aplicação; sem FK polimórfica)
                scope_id bigint NULL,
                value jsonb NOT NULL,
                updated_by bigint NULL REFERENCES users (id) ON DELETE SET NULL,
                created_at timestamptz NULL,
                updated_at timestamptz NULL,
                CONSTRAINT settings_scope_id_check CHECK ((scope_type = 'global') = (scope_id IS NULL))
            )
        SQL);

        // Um override por chave e escopo, inclusive o global (scope_id NULL): COALESCE iguala os NULLs.
        DB::unprepared('CREATE UNIQUE INDEX settings_key_scope_unique ON settings (key, scope_type, COALESCE(scope_id, 0))');
        DB::unprepared('CREATE INDEX settings_scope_idx ON settings (scope_type, scope_id)');
    }

    public function down(): void
    {
        DB::unprepared('DROP TABLE IF EXISTS settings');
    }
};
