<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        DB::unprepared(<<<'SQL'
            CREATE TABLE equipment_families (
                id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                code varchar(30) NOT NULL,
                name varchar(120) NOT NULL,
                category varchar(30) NOT NULL CHECK (category IN ('light_vehicle', 'truck', 'agri_machine', 'implement', 'support')),
                criticality varchar(10) NOT NULL DEFAULT 'medium' CHECK (criticality IN ('low', 'medium', 'high', 'critical')),
                -- campos da RN-001 futura (só persistência, sem motor): margem do pré-alerta e janela de aderência
                preventive_lead_pct numeric(5,2) NOT NULL DEFAULT 90.00 CHECK (preventive_lead_pct > 0 AND preventive_lead_pct <= 100),
                tolerance_km integer NULL CHECK (tolerance_km >= 0),
                tolerance_hours integer NULL CHECK (tolerance_hours >= 0),
                tolerance_days integer NULL CHECK (tolerance_days >= 0),
                is_active boolean NOT NULL DEFAULT true,
                created_at timestamptz NULL,
                updated_at timestamptz NULL,
                deleted_at timestamptz NULL
            )
        SQL);

        DB::unprepared('CREATE UNIQUE INDEX equipment_families_code_unique ON equipment_families (code) WHERE deleted_at IS NULL');
        DB::unprepared('CREATE INDEX equipment_families_category_idx ON equipment_families (category)');
    }

    public function down(): void
    {
        DB::unprepared('DROP TABLE IF EXISTS equipment_families');
    }
};
