<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        DB::unprepared(<<<'SQL'
            CREATE TABLE users (
                id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name varchar(120) NOT NULL,
                email varchar(190) NOT NULL,
                password varchar(255) NOT NULL,
                role varchar(20) NOT NULL CHECK (role IN ('operator', 'mechanic', 'leader', 'admin')),
                -- null = todas as filiais, permitido só para admin
                branch_id bigint NULL REFERENCES branches (id) ON DELETE RESTRICT,
                is_active boolean NOT NULL DEFAULT true,
                last_login_at timestamptz NULL,
                remember_token varchar(100) NULL,
                created_at timestamptz NULL,
                updated_at timestamptz NULL,
                deleted_at timestamptz NULL,
                CONSTRAINT users_branch_required_check CHECK (role = 'admin' OR branch_id IS NOT NULL)
            )
        SQL);

        DB::unprepared('CREATE UNIQUE INDEX users_email_unique ON users (email) WHERE deleted_at IS NULL');
        DB::unprepared('CREATE INDEX users_role_idx ON users (role)');
        DB::unprepared('CREATE INDEX users_branch_id_idx ON users (branch_id)');
    }

    public function down(): void
    {
        DB::unprepared('DROP TABLE IF EXISTS users');
    }
};
