<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        DB::unprepared(<<<'SQL'
            CREATE TABLE audit_logs (
                id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                uuid uuid NOT NULL UNIQUE,
                -- gerado pela aplicação (entra no hash); o default é só fallback e nunca entra no hash
                event_at timestamptz NOT NULL DEFAULT now(),
                source varchar(10) NOT NULL CHECK (source IN ('http', 'console', 'queue')),
                actor_id bigint NULL,
                actor_name varchar(120) NULL,
                actor_role varchar(20) NULL,
                action varchar(40) NOT NULL,
                auditable_type varchar(60) NULL,
                auditable_id bigint NULL,
                old_values jsonb NULL,
                new_values jsonb NULL,
                metadata jsonb NULL,
                ip inet NULL,
                user_agent varchar(255) NULL,
                request_id uuid NULL,
                prev_hash char(64) NOT NULL,
                hash char(64) NOT NULL
            )
        SQL);

        DB::unprepared('CREATE INDEX audit_logs_auditable_idx ON audit_logs (auditable_type, auditable_id)');
        DB::unprepared('CREATE INDEX audit_logs_actor_event_idx ON audit_logs (actor_id, event_at)');
        DB::unprepared('CREATE INDEX audit_logs_event_at_idx ON audit_logs (event_at)');
        DB::unprepared('CREATE INDEX audit_logs_action_idx ON audit_logs (action)');

        DB::unprepared(<<<'SQL'
            CREATE OR REPLACE FUNCTION audit_logs_immutable() RETURNS trigger
            LANGUAGE plpgsql AS $$
            BEGIN
                RAISE EXCEPTION 'audit_logs é append-only: % bloqueado', TG_OP USING ERRCODE = '42501';
            END;
            $$
        SQL);

        DB::unprepared('CREATE TRIGGER audit_logs_no_update_delete BEFORE UPDATE OR DELETE ON audit_logs FOR EACH ROW EXECUTE FUNCTION audit_logs_immutable()');
        DB::unprepared('CREATE TRIGGER audit_logs_no_truncate BEFORE TRUNCATE ON audit_logs FOR EACH STATEMENT EXECUTE FUNCTION audit_logs_immutable()');
    }

    public function down(): void
    {
        DB::unprepared('DROP TABLE IF EXISTS audit_logs');
        DB::unprepared('DROP FUNCTION IF EXISTS audit_logs_immutable()');
    }
};
